# wrangler.toml
name = 'git-demo'
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Import `.sql` files as strings (used by src/index.ts).
[[rules]]
globs = ["**/*.sql"]
type = "Text"
fallthrough = true

[assets]
directory = "./static"

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "ec9e8aa8-090a-42fa-964c-9797cad9fbdb"
